services:
  db:
    image: mysql:8.0
    container_name: eventflow_db
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - eventflow_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  backend:
    image: ghcr.io/nyakeruma-hezron/eventflow-v3-backend:latest
    container_name: eventflow_backend
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    volumes:
      - media_files:/app/media
      - static_files:/app/staticfiles
    depends_on:
      db:
        condition: service_healthy
    networks:
      - eventflow_net
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        python manage.py runserver 0.0.0.0:8000
      "

  frontend:
    image: ghcr.io/nyakeruma-hezron/eventflow-v3-frontend:latest
    container_name: eventflow_frontend
    restart: unless-stopped
    env_file: .env
    depends_on:
      - backend
    networks:
      - eventflow_net
    command: npm run dev -- --host 0.0.0.0

  nginx:
    image: ghcr.io/nyakeruma-hezron/eventflow-v3-proxy:latest
    container_name: eventflow_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - media_files:/media:ro
      - static_files:/static:ro
    depends_on:
      - backend
      - frontend
      - grafana
    networks:
      - eventflow_net
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    # NO ports exposed!
    restart: unless-stopped
    networks:
      - eventflow_net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      # Set your initial admin password here
      - GF_SECURITY_ADMIN_PASSWORD=@hez_ron3 
      # Critical: Tell Grafana it lives under a subpath behind a proxy
      - GF_SERVER_DOMAIN=nyx.name.ng
      - GF_SERVER_ROOT_URL=https://nyx.name.ng/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    # NO ports exposed!
    restart: unless-stopped
    depends_on:
      - prometheus
    networks:
      - eventflow_net  
volumes:
  mysql_data:
  media_files:
  static_files:
  prometheus_data:
  grafana_data:

networks:
  eventflow_net:
    driver: bridge